name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/install@v0.1
        with:
         crate: mdbook
         use-tool-cache: true
         version: "0.4.28"
      - uses: actions-rs/install@v0.1
        with:
         crate: mdbook-toc
         use-tool-cache: true
         version: "0.11.2"
      - uses: actions-rs/install@v0.1
        with:
         crate: mdbook-open-on-gh
         use-tool-cache: true
         version: "2.3.3"
      - name: Build book
        run: |
          PATH=.cargo/bin:$PATH mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
